packages:
  # all packages in direct subdirs of packages/
  - 'packages/**'
  # all packages in subdirs of libs/
  - 'libs/**'
  # all packages in subdirs of utils/
  - 'utils/**'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'